In [ ]:
#-----------------Python Arrays and Matrices------------------------

In [11]:
#--------Arrays--------------
#Create an array
cars = ["Ford", "Volvo", "BMW"]
#print the array
print(cars)

['Ford', 'Volvo', 'BMW']


In [12]:
#2.Extracting an element from array
print(cars[0])

Ford


In [13]:
#3.Replacing an element in array with some other
cars[0] = "Toyota"
print(cars)

['Toyota', 'Volvo', 'BMW']


In [14]:
#4.Length of the array.cars = ["Ford", "Volvo", "BMW"]
len(cars)

3

In [15]:
#5.Looping an array
for x in cars:
  print(x)

Toyota
Volvo
BMW


In [16]:
#5.Adding elements in an array
cars.append("Honda")
print(cars)

['Toyota', 'Volvo', 'BMW', 'Honda']


In [17]:
#6.Removing elements from an array
cars.pop(1)
print(cars)
#remove function 
cars.remove("Honda")
print(cars)

['Toyota', 'BMW', 'Honda']
['Toyota', 'BMW']


In [18]:
#7.Find the index of an element
cars.index("BMW")

1

In [21]:
#8.Reverse an array
cars.reverse()
print(cars)

['BMW', 'Toyota']


In [22]:
#9.Sorting the array
cars2 = ["Ford", "Volvo", "BMW","Honda"]
print(cars2)
cars2.sort()
print(cars2)

['Ford', 'Volvo', 'BMW', 'Honda']
['BMW', 'Ford', 'Honda', 'Volvo']


In [23]:
#------------------------------------MATRICES IN PYTHON--------------------------------------------------

In [24]:
#A matrix is a two-dimensional data structure where numbers are arranged into rows and columns.
#Python doesn't have a built-in type for matrices. However, we can treat list of a list as a matrix.
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]
print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row
column = [];        # empty list
for row in A:
  column.append(row[2])   
print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [5, 9, 11]


In [25]:
#NumPy is a package for scientific computing which has support for a powerful N-dimensional array object.
import numpy as np
a = np.array([1, 2, 3])
print(a)               
print(type(a)) 

[1 2 3]
<class 'numpy.ndarray'>


In [26]:
#An array of Integers, floats and complex numbers
A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)
A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)
A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[1.1 2.  3. ]
 [3.  4.  5. ]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [28]:
#Arrays of 0's and 1's
import numpy as np
zeors_array = np.zeros( (2, 3) )
print(zeors_array)
ones_array = np.ones( (1, 5), dtype=np.int32 )
print(ones_array)  

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]]


In [29]:
#Using arrange and shape
import numpy as np
A = np.arange(4)
print('A =', A)
B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [30]:
#Matrix operations
#1.Addition 
A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)
#2.Multiplications
A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = a.dot(B)
print(C)
#3.Transpose
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A.transpose())

[[11  1]
 [ 8  0]]
[14 -6]
[[ 1  2  3]
 [ 1  1 -3]]


In [32]:
#Access matrix elements, rows, columns
A = np.array([2, 4, 6, 8, 10])
print("A[0] =", A[0])         
print("A[2] =", A[2])     
print("A[-1] =", A[-1])

A[0] = 2
A[2] = 6
A[-1] = 10


In [33]:
A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])
#  First element of first row
print("A[0][0] =", A[0][0])  
# Third element of second row
print("A[1][2] =", A[1][2])
# Last element of last row
print("A[-1][-1] =", A[-1][-1])    

A[0][0] = 1
A[1][2] = 9
A[-1][-1] = 19


In [34]:
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])
print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

A[0] = [ 1  4  5 12]
A[2] = [-6  7 11 19]
A[-1] = [-6  7 11 19]


In [35]:
A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])
print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)

A[:,0] = [ 1 -5 -6]
A[:,3] = [12  0 19]
A[:,-1] = [12  0 19]


In [36]:
#Slicing of an array is similar to that of list.We will be performing array slicing on a 1D and 2D array
letters = np.array([1, 3, 5, 7, 9, 7, 5])
# 3rd to 5th elements
print(letters[2:5])        # Output: [5, 7, 9]
# 1st to 4th elements
print(letters[:-5])        # Output: [1, 3]   
# 6th to last elements
print(letters[5:])         # Output:[7, 5]
# 1st to last elements
print(letters[:])          # Output:[1, 3, 5, 7, 9, 7, 5]
# reversing a list
print(letters[::-1])          # Output:[5, 7, 9, 7, 5, 3, 1]

[5 7 9]
[1 3]
[7 5]
[1 3 5 7 9 7 5]
[5 7 9 7 5 3 1]


In [37]:
A = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])
print(A[:2, :4])  # two rows, four columns
print(A[:1,])  # first row, all columns
print(A[:,2])  # all rows, second column
print(A[:, 2:5])  # all rows, third to fifth column

[[ 1  4  5 12]
 [-5  8  9  0]]
[[ 1  4  5 12 14]]
[ 5  9 11]
[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]
